from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
# simplejwt views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

# DefaultRouter automatically creates the standard API routes (list, create, retrieve, update, destroy)
router = DefaultRouter()

# Register the ViewSets with the router.
# The first argument is the URL prefix for the endpoint (e.g., 'muscle-groups').
# The second argument is the ViewSet class to handle requests for that prefix.
# The optional 'basename' is needed if the ViewSet doesn't have a '.queryset' attribute or if you customize the queryset (like in PlanViewSet/WorkoutViewSet).
# It helps in generating URL names.
router.register(r'muscle-groups', views.MuscleGroupViewSet)
router.register(r'exercises', views.ExerciseViewSet)
router.register(r'workouts', views.WorkoutViewSet, basename='workout')
router.register(r'plans', views.PlanViewSet, basename='plan')
# Optional: If you created a UserViewSet, register it here
# router.register(r'users', views.UserViewSet)

# The API URLs are now determined automatically by the router.
# The 'urlpatterns' list includes the URLs generated by the router.
urlpatterns = [
    # This includes all the URLs registered with the router above.
    # Requests to '/api/muscle-groups/', '/api/exercises/1/', etc., will be handled.
    path('', include(router.urls)),

    # Authentication URLs
    path('auth/register/', views.RegisterView.as_view(), name='auth_register'),

    path('auth/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),

    path('auth/login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
